CREATE TABLE IF NOT EXISTS urls(
    id BIGSERIAL PRIMARY KEY,
    long_url VARCHAR(200) NOT NULL,
    short_url VARCHAR(200) NOT NULL,
    created_date TIMESTAMP NOT NULL,
    expire_date TIMESTAMP NOT NULL
);